version: '3.7'
services:
    rp:
        image: traefik:v2.2
        command: 
            - "--api.insecure=true" 
            - "--providers.docker=true"
        ports: 
            - "80:80"
            - "8080:8080"
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock

    ui:
        build: front-end
        image: sc-ui
        container_name: sc-ui
        stdin_open: true
        volumes: 
            - "./front-end:/app:rw"
        labels:
            - "traefik.http.routers.ui.rule=PathPrefix(`/old/`)"
            - "treafik.http.services.ui.loadbalancer.server.port=3000"
    ng-ui:
        build: angular-front-end
        image: ng-ui
        container_name: ng-ui
        volumes: 
            - './angular-front-end:/app'
            - '/app/node_modules'
        labels:
            - "traefik.http.routers.ng-ui.rule=PathPrefix(`/`)"
            - "treafik.http.services.ng-ui.loadbalancer.server.port=4200"
    api:
        build: back-end
        image: sc-api
        container_name: sc-api
        volumes:
            - "./back-end:/app:rw"
        labels:
            - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"
            - "treafik.http.services.api.loadbalancer.server.port=5000"
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: sc
            POSTGRES_PASSWORD: api-password
            POSTGRES_DB: scdb